name: Vercel webhook
on:
  push:
    branches: [master]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Triggering deploy hook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.VERCEL_WEBHOOK_PRODUCTION }}
          method: 'POST'
